### ISSUE TITLE
The media collection is not displayed

### ISSUE THREAD

**Issue by YulKard** [adminarchitect/core#10]
Hello! I update AdminArchitect in my project and try to use media collection in my model. 
In my model:
`namespace App\Model;

use Illuminate\Database\Eloquent\Model;
use Codesleeve\Stapler\ORM\StaplerableInterface;
use Codesleeve\Stapler\ORM\EloquentTrait;
use Spatie\MediaLibrary\Media;
use Spatie\MediaLibrary\HasMedia\Interfaces\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;

class Transport extends Model implements StaplerableInterface, HasMedia
{

    use EloquentTrait,
        HasMediaTrait;

    protected $fillable = [
        'title', 'number', 'owner', 'carrier_id', 'status', 'ownership', 'image', 'passport', 'insurance', 'proxy', 'sanitary',
        'type', 'bodywork', 'width', 'height', 'lenght', 'empty_speed', 'loaded_speed', 'type_discharge', 'carrying_capacity', 'volume'
    ];
    public function getAttributes()
    {
        return parent::getAttributes();
    }
`

In my Resource:
`public function form()
    {
        return $this->scaffoldForm()
                        ->media('images', function (FormElement $element) {
                            // @var $media MediaElement
                            $media = $element->getInput();
                            $media->hasArrows(true)            
                            ->hasIndicators(true)       
                            ->convertedTo('thumbnail')    
                            ->autoPlay(2)                 
                            ->maxWidth(200);        
                        });
    }`

But field for download images don't display http://joxi.ru/xAe0z0zup118R2. I am checked the view for media in my view folder and she is.
Maybe I missed something? 
Thank you in advance.

**Comment by endihunter** [comment]
Hello,

Seems that you missed the updating assets step:

1. make sure you've updated the resources/assets/administrator directory from the latest AA version

2. use latest npm's https://www.npmjs.com/package/adminarchitect-mix version

3. rebuild your assets by running: npm run [dev|prod]

**Comment by YulKard** [comment]
Ok! I will try it. Thank you!
