### ISSUE TITLE
Issues installing with Laravel 5.6

### ISSUE THREAD

**Issue by daylightstudio** [adminarchitect/core#15]
Running `composer require adminarchitect/core` with Laravel 5.6 is throwing the error:
```
Your requirements could not be resolved to an installable set of packages.
```
Seems to be compatibility issues with the codesleeve package?

**Comment by devmsh** [comment]
any plans?

**Comment by endihunter** [comment]
there are few issues why we still don't support laravel 5.6:
1. it depends on codesleeve/laravel-stapler which still doesn't support laravel 5.6 (already working on it)
2. conflicts with bootstrap versions: laravel 5.6 uses BS4, while AA - 3, so it requires time to fix it.

**Comment by powerpbx** [comment]
I tried downgrading to Laravel 5.5 and still ran into a version problem.
it does not like symfony/translation v4.*
I had to add the following to `composer.json`

`"symfony/translation": "3.4.6"`

**Comment by endihunter** [comment]
@powerpbx not sure about downgrading, but it should work with Laravel 5.5 fresh installation.

**Comment by powerpbx** [comment]
It is happening on Laravel v5.5 fresh install. 

`composer create-project laravel/laravel someproject "5.5"`
`cd someproject`
`composer require adminarchitect/core`

```
Using version ^1.5 for adminarchitect/core
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install adminarchitect/core v1.5.2
    - Conclusion: don't install adminarchitect/core v1.5.1
    - Conclusion: remove symfony/translation v4.0.6
    - Installation request for adminarchitect/core ^1.5 -> satisfiable by adminarchitect/core[v1.5, v1.5.1, v1.5.2].
    - Conclusion: don't install symfony/translation v4.0.6
```

**Comment by endihunter** [comment]
@powerpbx you're right, it doesn't work, but the funniest part is AA doesn't require symfony/translation package. need to figure out at which dependency it comes from...

**Comment by powerpbx** [comment]
Unfortunately I cannot complete the install.  I have hit npm problems now.  If you go through the install you should be able to reproduce unless I did something wrong.

```
npm run dev

> @ dev /var/www/html/adminarch1
> npm run development


> @ development /var/www/html/adminarch1
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn node_modules/webpack/bin/webpack.js ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

**Comment by endihunter** [comment]
@powerpbx it's very often npm issue - sometimes it just doesn't work..., follow the steps:
1. remove node_modules directory
2. add `"adminarchitect-mix": "^1.1"` to `devDependencies` section in `package.json`
3. run `npm install` or `yarn`
4. make sure you published the AA assets by: `php artisan administrator:publish` and directory `resources/assets/administrator` exists and not empty.
5. add: 
`let aa = require('adminarchitect-mix');`
`(new aa).handle();` to `webpack.mix.js` file;
6. run `[npm|yarn] run dev`

... let me know if it helps!

**Comment by powerpbx** [comment]
Thanks for the suggestions.  Unfortunately it didn't appear to help.

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'dev' ]
2 info using npm@5.7.1
3 info using node@v8.10.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle @~predev: @
6 info lifecycle @~dev: @
7 verbose lifecycle @~dev: unsafe-perm in lifecycle true
8 verbose lifecycle @~dev: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/var/www/html/adminarch1/node_modules/.bin:/root/.config/composer/vendor/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
9 verbose lifecycle @~dev: CWD: /var/www/html/adminarch1
10 silly lifecycle @~dev: Args: [ '-c', 'npm run development' ]
11 silly lifecycle @~dev: Returned: code: 1  signal: null
12 info lifecycle @~dev: Failed to exec dev script
13 verbose stack Error: @ dev: `npm run development`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid @
15 verbose cwd /var/www/html/adminarch1
16 verbose Linux 2.6.32-042stab127.2
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "dev"
18 verbose node v8.10.0
19 verbose npm  v5.7.1
20 error code ELIFECYCLE
21 error errno 1
22 error @ dev: `npm run development`
22 error Exit status 1
23 error Failed at the @ dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by dlaynes** [comment]
Hi, is this thread related?

https://github.com/JeffreyWay/laravel-mix/issues/1016

**Comment by powerpbx** [comment]
In my case, I think it is this OS dependent problem.  I am using CE7.

https://github.com/JeffreyWay/laravel-mix/issues/1539

I got past that with `yum install libpng-devel`

That gets me further along in the install but now  I have compile errors with files in ../resources/asssets/administrator/js  .

**Comment by endihunter** [comment]
@powerpbx did you publish AA resources by running `php artisan administrator:publish` command? Please make sure the `resources/assets/administrator` folder is not empty.

**Comment by powerpbx** [comment]
I have re-installed from scratch several times following all required steps and verified that the required folders exist.

I can't really use this product until it is compatible with v5.6 anyways.  I know it may be awhile but I will have to wait.

**Comment by endihunter** [comment]
@daylightstudio @powerpbx @devmsh just committed some stuff, to make it ready for laravel 5.6.
please, let me know if it solves the compatibility issues. Just make sure you're installing dev-master branch. 
Thanks.

**Comment by AbbyJanke** [comment]
@endihunter - This is my first experience with AdminArchitect, was looking at various admin panels, but dev-master still does not install for the same reason as issue was started. Cheers.

**Comment by endihunter** [comment]
@AbbyJanke it should work now. Fixed dependencies, used old version.
Please run `composer clear-cache` before. Thanks

**Comment by AbbyJanke** [comment]
@endihunter I got everything installed except for styles. But here's what i got when running `npm run dev` It seems to do most of the styling, but probably just not some of the bootstrap plugins which does cause an error (shown below)

```
* @adminarchitect/bootstrap-datepicker in ./resources/assets/administrator/js/vendor.js
* @adminarchitect/bootstrap-daterangepicker in ./resources/assets/administrator/js/vendor.js
* @adminarchitect/bootstrap/js/alert in ./resources/assets/administrator/js/vendor.js
* @adminarchitect/bootstrap/js/carousel in ./resources/assets/administrator/js/vendor.js
* @adminarchitect/bootstrap/js/collapse in ./resources/assets/administrator/js/vendor.js
* @adminarchitect/bootstrap/js/dropdown in ./resources/assets/administrator/js/vendor.js
* @adminarchitect/bootstrap/js/modal in ./resources/assets/administrator/js/vendor.js
* @adminarchitect/bootstrap/js/tab in ./resources/assets/administrator/js/vendor.js
* @adminarchitect/bootstrap/js/transition in ./resources/assets/administrator/js/vendor.js
* @adminarchitect/jquery-toggles/toggles in ./resources/assets/administrator/js/vendor.js
```

```
"Undefined index: /admin/vendor.css (View: /Users/abby/Sites/architect/resources/views/vendor/administrator/partials/styles.blade.php) (View: /Users/abby/Sites/architect/resources/views/vendor/administrator/partials/styles.blade.php) (View: /Users/abby/Sites/architect/resources/views/vendor/administrator/partials/styles.blade.php)
```

If I remove the html link for `admin/vendor.css` i have no issues.

This is with a fresh install and copy/pasting from the documentations. Also a note, running 'npm i yarn' is necessary and not mentioned in the docs.
