### ISSUE TITLE
Problem with Saver

### ISSUE THREAD

**Issue by YulKard** [adminarchitect/core#17]
Good day. 
I want to send a message to user, when admin register him. I creates a Saver Users.php. But when I add a function sync() and called parent method sync I have an error http://joxi.ru/nAy8E8EuY0ZXw2 but element was saved.
In this place eloquent  rerurns as NULL.   If you edit the element, then everything works correctly.
My Saver http://joxi.ru/D2PQbQbtpP7deA.
I have the latest version of AdminArchitect.
 Please, tell what is wrong. Thank you for advance.

**Comment by endihunter** [comment]
@YulKard you should return the repository, your code doesn't return it.
