### ISSUE TITLE
Usage Translateble and StaplerableInterface together

### ISSUE THREAD

**Issue by YulKard** [adminarchitect/core#25]
Hello! I have a problem with using HasTranslations and EloquentTrait in my model. I have problem with methods getAttribute and setAttribute, so I redefined them:
http://joxi.ru/krDDZDZSEb8okr
But I have error with image, when I save a data http://joxi.ru/l2Z6a6auwxpG92.
When I removed HasTranslations and Translatable, image successfully saved. 
Plaese, tell me what iam doing wrong. Trank you for advance.

**Comment by endihunter** [comment]
Hello, to solve methods collision between Translatable & Stapler packages,  try this workaround: https://gist.github.com/endihunter/ab1c83f5108465c5cf71ff810629007b

**Comment by YulKard** [comment]
Thank you. I will try.
