### ISSUE TITLE
Datetime type is provided, but yields date

### ISSUE THREAD

**Issue by dinandmentink** [adminarchitect/core#27]
When using a datetime input type the `Terranet\Administrator\Form\Type\Datetime` is correctly selected. 

Expected behaviour: this element has a datetime selector (eg bootstrap-datetimepicker)
Actual behaviour: this element has a date selector.

If interested I can make a PR against `adminarchitect/core` and `adminarchitect/mix` to include a datetimepicker element. But wanted to check if this would be appreciated first.

Reproduce by: 

- make a new module that includes, for example:

```
public function form()
    {
        return $this
        ->scaffoldForm()
        ->update('party_at', function($e){ return $e->setInput('datetime'); });
    }
```

**Comment by endihunter** [comment]
@dinandmentink it's fixed. Thanks for reporting the issue.

**Comment by dinandmentink** [comment]
Thank you :+1:

**Comment by endihunter** [comment]
@dinandmentink to make it working, you need to update adminarchitect/core and install the latest version of @adminarchitect/mix.

**Comment by dinandmentink** [comment]
Thanks. I'll do so. 

Have you seen my PR against /mix? It seems npm doesnt resolve daterangepicker correctly.

**Comment by dinandmentink** [comment]
Question. the latest version of @adminarchitect/mix isn't updated since october. Has there been a release specific for this issue?

**Comment by endihunter** [comment]
@dinandmentink it's not updated on github, but npmjs contains the latest version
