### ISSUE TITLE
How can I upload a image to my custom directory?

### ISSUE THREAD

**Issue by filip-mustatea** [adminarchitect/core#34]
Hello,

I set a field from a form to be for image uploads like this :

` public function form()
    {
        return $this
            ->scaffoldForm()

            # Update existing column
            ->update('image', function ($element) {

                # Set a different input type
                $element->setInput(
                    new Image('image')
                );

                return $element;
            });
    }`

But my images are saved in a temporary folder with extension .tmp.
How can I set my folder?

Thank you!

**Comment by endihunter** [comment]
@filip-mustatea adminarchitect uses [paperclip](https://github.com/czim/laravel-paperclip) for images/files management. Please read its documentation for customisation.

**Comment by endihunter** [comment]
@filip-mustatea also, please follow these [documentation steps](http://docs.adminarchitect.com/#/Forms/forms?id=files-amp-images).
