### ISSUE TITLE
How to display relation's table field?

### ISSUE THREAD

**Issue by Stiropor** [adminarchitect/core#35]
This is an awesome project! But I have one problem - I can't find in any documentation or here anywhere how to display a field from related table. My **events** table has a **client_id** field, that points to **clients** table. In grid right now the data is displayed at 1. How do I make it dispay's client's name (title field)? I know I need to use `update()` in `columns()` method, but how? I see that works just fine in your demo app ... but cannot figure what is the correct way of doing it except manually doing search on Client model... is this the only/right way?

2 more questions:
- is that demo site available to download/check anywhere? It'd probably be a great help for users!
- I see this project is also on codecanyon... what's the difference? I'd gladly support this project, would just like to know what the difference between github's version and one from cc is?

**Comment by endihunter** [comment]
Hello.

To display the relations fields, just include them in list of columns
`$this->push('client.name')` with name: 'relationname.fieldname', or in
your case 'client.name'.
Remember this assumes you have a relation 'client()' in your User model.

There is no difference between cc version and github one. Cc was just for
support, and now its easier to "buy a coffee" instead ;)

**Comment by Stiropor** [comment]
Oh, so basicaly I don't **change** the client_id but **add** client and then hide client_id column. Cool. Thanks!

**Comment by Stiropor** [comment]
2 bugs (I think) I just found:

1. push doesn't have a position parameter, so I have to use `move()`. But if I assign ID to `client.name` in closure, client.name isn't displayed. If I don't assing it, it works, but I have to assign it in order to change it's position.

2. if I use `insert('client.name', ...)` and current model also has a name (event.name), it will display event.name instead of client.name. Inserting any other client's field that event doesn't have, works as expected.

I see this app is getting currently updated? The UI is way different than the one on demo. Keep up the good work :)

**Comment by smallcar88** [comment]
Hello @endihunter,

I would like to ask how to add a form element based on a user role? 
Like I have a model `User` with roles of `admin`, `seller`, `user`
I don't want a user record to have an image uploader on the form. How can I conditionally add the form element based on the role value? 

thanks!

**Comment by endihunter** [comment]
@smallcar88  I think something like this should work.

```
public function form() {
    $form = $this->scaffoldForm();

    if (auth()->user()->isAdmin()) {
        $form->push(FormElement::media('image_uploader'));
    }

    return $form;
}
```

**Comment by endihunter** [comment]
@smallcar88 or if you want to disable an element for specific user:

```
... get form
if (auth()->user()) {
   $form->without('image_uploader');
}

return $form;
```

**Comment by endihunter** [comment]
> of if you want to disable an element for specific user:
> 
> ```
> ... get form
> if (auth()->user()) {
>    $form->without('image_uploader');
> }
> 
> return $form;
> ```

**Comment by smallcar88** [comment]
@endihunter thank you for the answer. 
Actually my question is at per-record level, not the current user.
For example, `user:1` is a seller, `user:2` is a normal user.
When I edit their profiles as an admin, I want the form of the seller to have `image` uploader, but not in that of a normal user. 
Is it achievable via form() function?

**Comment by endihunter** [comment]
> @endihunter thank you for the answer.
> Actually my question is at per-record level, not the current user.
> For example, `user:1` is a seller, `user:2` is a normal user.
> When I edit their profiles as an admin, I want the form of the seller to have `image` uploader, but not in that of a normal user.
> Is it achievable via form() function?

@smallcar88 so, in your case just use the `app('scaffold.model')` instead of `auth()->user()`.
that will give you the model you're working on instead of logged in user.

**Comment by smallcar88** [comment]
Thank you so much @endihunter, your solution works great for me! Much Appreciated!
