### ISSUE TITLE
Any form element to handle array of object?

### ISSUE THREAD

**Issue by smallcar88** [adminarchitect/core#39]
Hi there,
Thank you for writing such a good admin panel for Laravel. I got lots of inspiration and saved tons of time of making the admin panel. 

One question is that on Laravel we can have attribute being defined as "array" or "json" (which is an array of object), is there any form element to handle this kind of model attributes? 

Right now I am thinking to extends the basic Form\Element and write my own handling element. Is that the right way to do so? 

Thanks!

**Comment by endihunter** [comment]
@smallcar88 unfortunately there is no `json` editor connected (it might appear in version 2), but just to be able to edit it - I think you can use simple `textarea` element, or you might consider using `FormElement::view` element which is a basic way to build a very custom field types.
