### ISSUE TITLE
is this package abandoned?

### ISSUE THREAD

**Issue by mojtabaahn** [adminarchitect/core#42]
Hi there
Seems it is abandoned to me

It's a few days I'm searching around for laravel crud builders, panels and anything that can compete with Laravel nova and i found Admin Architect and to me it's awesome! it has many things that Nova has and amazing part is that it had it all before even nova comes out! and It's not just a simple crud builder like many ones out there.

but the fact that this packages has no commits since like 3 months and the community haven't discovered its potentials is so shocking to me.

so i wonder what is your vision about AA's future!

thanks.

**Comment by endihunter** [comment]
@mojtabaahn  Hello. It's still alive. The new version is in progress, but I'm agree with you - it is not so motivating to work on a project, when community is so passive :(.
