### ISSUE TITLE
Laravel 5.8 support

### ISSUE THREAD

**Issue by dinandmentink** [adminarchitect/core#55]
Upon trying to migrate to laravel 5.8 I ran into this error:

```
Access level to Czim\Paperclip\Model\PaperclipTrait::originalIsEquivalent() must be public (as in class Illuminate\Database\Eloquent\Model)
```

It seems the `Czim\Paperclip` dependency used is incompatible with laravel 5.8. Is there any chance of upgrading the dependency?

**Comment by endihunter** [comment]
@dinandmentink fixed, it uses now the paperclip 2.7
