### ISSUE TITLE
Request: Plugins / Packages

### ISSUE THREAD

**Issue by vanvanni** [adminarchitect/core#63]
Dear,

Again I have said it in another issue but this is a great and simple package. And I would love to contribute in a way of saving time. Having plugins or packages to simply extend your own AA with the existing code would be nice. 

E.G. A package that will create an interface for `https://github.com/spatie/laravel-permission`

**Comment by endihunter** [comment]
@xJoeyv a spectrum channel ([Resources](https://spectrum.chat/adminarchitect/resources?tab=posts)) has been created, so you can share your ideas there, thanks!
