### ISSUE TITLE
Spatie medialibrary v7 support

### ISSUE THREAD

**Issue by dinandmentink** [adminarchitect/core#64]
Hello,

Are there any plans for supporting spatie/laravel-medialibrary v7. It seems as of now only v6 is supported.

Anyone familiar with a monkeypatch that can help me to get v7 to work?

**Comment by dinandmentink** [comment]
After some fiddling around I found that, when running medialibrary v7 the only requirements to getting it to run is to create:

Spatie\MediaLibrary\HasMedia\HasMedia and extend it from Spatie\MediaLibrary\HasMedia\Interfaces\HasMedia;

And Spatie\MediaLibrary\Models\Media; extending from Spatie\MediaLibrary\Media;

**Comment by dinandmentink** [comment]
Small update. It is possible to amend Saver.php to

```
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaConversions;
```

and Media.php to
```
use Spatie\MediaLibrary\Models\Media as MediaItem;
```

And then adminarchitect works perfectly with medialibrary v7. I have done so now in a monkeypatch. Do you want me to submit a PR for this?

**Comment by endihunter** [comment]
@dinandmentink yep, sure you can submit a PR, thanks
