### ISSUE TITLE
add try..catch to delete action

### ISSUE THREAD

**Issue by zoryamba** [adminarchitect/core#72]
Could you please add try..catch block in delete action of ScaffoldController to handle deleting errors? It could be useful when you want to restrict deleting when model has related models. For instance restrict category deleting if category has some products included. Seems to be a common case.

**Comment by endihunter** [comment]
@zoryamba your PR is merged now, thanks for contribution!

**Comment by zoryamba** [comment]
@endihunter could you please update composer package? maybe it could be automated?
