### ISSUE TITLE
Problem installing

### ISSUE THREAD

**Issue by ghost** [adminarchitect/core#78]
Hi there,

I'm having some trouble installing adminarchitect. I created a new project (Laravel 6) and added adminarchitect (^2.0). I've published using the command: `php artisan administrator:publish` (using default: yes, no, yes), but it does not create the `resources/assets/administrator` directory and the `app\Http\Terranet\Administrator\Navigation.php` file. No error is given but I can't find the directory or file in the project structure. (I'm running this at windows 10 as administrator).

After that I've installed the packages and tried to compile it using `npm run dev`, but here I got the error: 

> These dependencies were not found:
> 
> * C:\Programming\adminarchitect\resources\assets\administrator\js\app.js in multi ./resources/assets/administrator/js/app.js
> * C:\Programming\adminarchitect\resources\assets\administrator\js\editors\ckeditor.js in multi ./resources/assets/administrator/js/editors/ckeditor.js
> * C:\Programming\adminarchitect\resources\assets\administrator\js\editors\medium.js in multi ./resources/assets/administrator/js/editors/medium.js
> * C:\Programming\adminarchitect\resources\assets\administrator\js\editors\tinymce.js in multi ./resources/assets/administrator/js/editors/tinymce.js
> * C:\Programming\adminarchitect\resources\assets\administrator\js\theme.js in multi ./resources/assets/administrator/js/theme.js
> * C:\Programming\adminarchitect\resources\assets\administrator\js\vendor.js in multi ./resources/assets/administrator/js/vendor.js
> * C:\Programming\adminarchitect\resources\assets\administrator\less\glyphicons.less in multi ./resources/js/app.js ./resources/assets/administrator/less/glyphicons.less ./resources/sass/app.scss ./resources/assets/administrator/sass/app.scss ./resources/assets/administrator/sass/vendor.scss ./resources/assets/administrator/sass/editors/medium.scss
> * C:\Programming\adminarchitect\resources\assets\administrator\sass\app.scss in multi ./resources/js/app.js ./resources/assets/administrator/less/glyphicons.less ./resources/sass/app.scss ./resources/assets/administrator/sass/app.scss ./resources/assets/administrator/sass/vendor.scss ./resources/assets/administrator/sass/editors/medium.scss
> * C:\Programming\adminarchitect\resources\assets\administrator\sass\editors\medium.scss in multi ./resources/js/app.js ./resources/assets/administrator/less/glyphicons.less ./resources/sass/app.scss ./resources/assets/administrator/sass/app.scss ./resources/assets/administrator/sass/vendor.scss ./resources/assets/administrator/sass/editors/medium.scss
> * C:\Programming\adminarchitect\resources\assets\administrator\sass\vendor.scss in multi ./resources/js/app.js ./resources/assets/administrator/less/glyphicons.less ./resources/sass/app.scss ./resources/assets/administrator/sass/app.scss ./resources/assets/administrator/sass/vendor.scss ./resources/assets/administrator/sass/editors/medium.scss
> 
> To install them, you can run: npm install --save C:\Programming\adminarchitect\resources\assets\administrator\js\app.js C:\Programming\adminarchitect\resources\assets\administrator\js\editors\ckeditor.js C:\Programming\adminarchitect\resources\assets\administrator\js\editors\medium.js C:\Programming\adminarchitect\resources\assets\administrator\js\editors\tinymce.js C:\Programming\adminarchitect\resources\assets\administrator\js\theme.js C:\Programming\adminarchitect\resources\assets\administrator\js\vendor.js C:\Programming\adminarchitect\resources\assets\administrator\less\glyphicons.less C:\Programming\adminarchitect\resources\assets\administrator\sass\app.scss C:\Programming\adminarchitect\resources\assets\administrator\sass\editors\medium.scss C:\Programming\adminarchitect\resources\assets\administrator\sass\vendor.scss
> Error: ENOENT: no such file or directory, stat 'C:\Programming\adminarchitect\resources\assets\administrator\images'
>     at Object.statSync (fs.js:850:3)
>     at Object.statSync (C:\Programming\adminarchitect\node_modules\graceful-fs\polyfills.js:308:16)
>     at checkStats (C:\Programming\adminarchitect\node_modules\fs-extra\lib\copy-sync\copy-sync.js:171:22)
>     at checkPaths (C:\Programming\adminarchitect\node_modules\fs-extra\lib\copy-sync\copy-sync.js:183:31)
>     at Object.copySync (C:\Programming\adminarchitect\node_modules\fs-extra\lib\copy-sync\copy-sync.js:25:20)
>     at File.copyTo (C:\Programming\adminarchitect\node_modules\laravel-mix\src\File.js:191:12)
>     at FileCollection.copyTo (C:\Programming\adminarchitect\node_modules\laravel-mix\src\FileCollection.js:83:24)
>     at src.forEach.file (C:\Programming\adminarchitect\node_modules\laravel-mix\src\FileCollection.js:77:38)
>     at Array.forEach (<anonymous>)
>     at FileCollection.copyTo (C:\Programming\adminarchitect\node_modules\laravel-mix\src\FileCollection.js:77:17)
>     at CopyFilesTask.run (C:\Programming\adminarchitect\node_modules\laravel-mix\src\tasks\CopyFilesTask.js:15:20)
>     at CustomTasksPlugin.runTask (C:\Programming\adminarchitect\node_modules\laravel-mix\src\webpackPlugins\CustomTasksPlugin.js:36:14)
>     at Mix.tasks.forEach.task (C:\Programming\adminarchitect\node_modules\laravel-mix\src\webpackPlugins\CustomTasksPlugin.js:12:44)
>     at Array.forEach (<anonymous>)
>     at compiler.plugin.stats (C:\Programming\adminarchitect\node_modules\laravel-mix\src\webpackPlugins\CustomTasksPlugin.js:12:23)
>     at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Programming\adminarchitect\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:18:1)
>     at AsyncSeriesHook.lazyCompileHook (C:\Programming\adminarchitect\node_modules\tapable\lib\Hook.js:154:20)
>     at emitRecords.err (C:\Programming\adminarchitect\node_modules\webpack\lib\Compiler.js:304:22)
>     at Compiler.emitRecords (C:\Programming\adminarchitect\node_modules\webpack\lib\Compiler.js:499:39)
>     at emitAssets.err (C:\Programming\adminarchitect\node_modules\webpack\lib\Compiler.js:298:10)
>     at hooks.afterEmit.callAsync.err (C:\Programming\adminarchitect\node_modules\webpack\lib\Compiler.js:485:14)
>     at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Programming\adminarchitect\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:20:1)
>     at AsyncSeriesHook.lazyCompileHook (C:\Programming\adminarchitect\node_modules\tapable\lib\Hook.js:154:20)
>     at asyncLib.forEachLimit.err (C:\Programming\adminarchitect\node_modules\webpack\lib\Compiler.js:482:27)
>     at C:\Programming\adminarchitect\node_modules\neo-async\async.js:2818:7
>     at done (C:\Programming\adminarchitect\node_modules\neo-async\async.js:3522:9)
>     at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Programming\adminarchitect\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
>     at outputFileSystem.writeFile.err (C:\Programming\adminarchitect\node_modules\webpack\lib\Compiler.js:464:33)
>     at C:\Programming\adminarchitect\node_modules\graceful-fs\graceful-fs.js:57:14
>     at FSReqWrap.args [as oncomplete] (fs.js:140:20)

I think the problem is that the publish doesn't work as intended.

**Comment by endihunter** [comment]
@GuidoThomassen in version 2 assets are not published in resources/assets/administrator directory... they are published into a `<project root>/adminarchitect-mix` directory.
so just cd into that directory and run `npm i && npm run dev` command
